# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - appkaouthar

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://kaoutharcontainer.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_2ac675cbb6ca479a807bb9f57c70822e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_d33204a98e4a4ed89662180b9d052adf }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: kaoutharcontainer.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_2ac675cbb6ca479a807bb9f57c70822e }}/kaoutharcontainer/cvapp:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'appkaouthar'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_5aeeb5174b3f4594aec93c7d3f616ea1 }}
        images: 'kaoutharcontainer.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_2ac675cbb6ca479a807bb9f57c70822e }}/kaoutharcontainer/cvapp:${{ github.sha }}'